### ISSUE TITLE
Upgrade to pydantic v2

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/pipeline#159]
Pydantic v2 [has arrived](https://docs.pydantic.dev/latest/blog/pydantic-v2-final/) 🎉

It's chock full of breaking changes but they have a very comprehensive looking [migration guide](https://docs.pydantic.dev/latest/migration/)!  A quick initial poke at this shows that our root_validators are the main thing which need updating.

**Comment by lucyb** [comment]
Can you do https://github.com/opensafely-core/pipeline/issues/183 as soon as this is merged please? That way, if there are any changes that affect our code we'll know quicky.
