### ISSUE TITLE
Create a version 4.0 format which doesn't include the `expectations` section

### ISSUE THREAD

**Issue by evansd** [opensafely-core/pipeline#224]
The `expectations` configuration e.g.
```yaml
expectations:
  population_size: 1000
```
is no longer used by ehrQL, and therefore we should get rid of it.

However it is currently required by version 3.0 of the `project.yaml` format:
https://github.com/opensafely-core/pipeline/blob/8c706d663fb2fcae279bc0f15c1b1b3bd4314e99/pipeline/features.py#L6-L10
https://github.com/opensafely-core/pipeline/blob/8c706d663fb2fcae279bc0f15c1b1b3bd4314e99/pipeline/models.py#L186-L211

Version 4.0 should reject this section.

Once we have done this we should update the [research-template](https://github.com/opensafely/research-template) accordingly.

See also:
 * https://github.com/opensafely/research-template/pull/110#discussion_r1384738988

**Comment by lucyb** [comment]
After speaking with Peter, this doesn't sound urgent and could be done by the upcoming RAP Team rather than the current Pipeline Team. Please let me know if I've missed anything.

**Comment by inglesp** [comment]
When we introduce version 4, we'll also want to raise a validation error if there are any cohort-extractor actions in a project.yaml.

Additionally, we should:

- [ ] update the pipeline.yaml example in the [research template](https://github.com/opensafely/research-template/blob/main/project.yaml)
- [ ] ensure that all examples at docs.opensafely.org use version 4 and don't include an expectations section.

**Comment by alarthast** [comment]
Before we update the research template, we need to first test that a `project.yaml` file using v4 and no expectation sections does not break anything. The steps to do this are:
[ ] Merge #341 
[ ] Create a new release following DEVELOPERS.md
[ ] Update job-runner to use the new release of pipeline, which will build a new job-runner release
[ ] Update opensafely-cli 's vendoring of job-runner
[ ] Use opensafely-cli on a project.yaml file with v4 and test that everything works

then, do the two tasks listed in Peter's comments above
